### ISSUE TITLE
Conda install

### ISSUE THREAD

**Issue by rpetit3** [jhawkey/IS_mapper#37]
Hi Jane, 

I've been making use of ISMapper in a recent Hflu study we are working on. It has been very useful, thank you very much for a great tool! 

I've recently set up a conda install for v2.0 under my personal Anaconda account.  It is available here: [rpetit3/ismapper](https://anaconda.org/rpetit3/ismapper) and can be installed via `conda create -n ismapper-env -c rpetit3 ismapper`

I've run your example test and get the expected output (md5sums match). I can rerun it on a the samples I used it for previously, if you'd like. Ultimately, with your permission I would like to submit this to Bioconda.

Thanks again!
Robert

**Comment by jhawkey** [comment]
Hey Robert,

Thanks for doing this! This has been on my wishlist for a while but I just hadn't gotten around to working out how to do it. Glad to hear that the test data returns the correct result.

I'm happy for you to submit this to bioconda when you're ready - when you've done so I'll update the install instructions.

**Comment by rpetit3** [comment]
No problem! Here's the about section for the recipe, let me know if it works or if you want to change anything. The summary was taken from the publication.

Also, should I name the recipe `is_mapper` (like repo) or `ismapper`
```
about:
  home: https://github.com/jhawkey/IS_mapper/
  license: BSD
  license_file: LICENSE.txt
  summary: A mapping-based tool for identification of the site and orientation of IS insertions in bacterial genomes.
```
